### ISSUE TITLE
DayView - Remaining Time Field Not Updating Properly

### ISSUE THREAD

**Issue by MattLCoder** [DavePCoder/CTMS-Issues#36]
**CTMS version being used (e.g. CTMS v5.0 alpha 1 Build 102)**
Which version of CTMS is the bug found in?
Alpha 1, build 103

**Describe the bug**
As title.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open DayView - select day with no booking codes applied
2. Select booking codes and Add Task
3. Close DayView and then reopen DayView on same day
4. Alter the time value for any of the selected booking codes

**Expected behaviour**
Alterations to Existing booking tasks fail to update the 'Remaining Time' field.

When the user opens the DayView on any available day and then adds new booking code tasks to the list the 'Remaining Time' field located below the available programmes list will correctly update to reflect the 20mins automatic slots made when adding a task. The Remaining Time field will also update correctly if the time value of a newly entered task is altered while remaining in this instance of DayView.
Once the user leaves the DayView and goes back to the main app, then returns to the DayView of the selected day, any alterations to the time value of the saved booking tasks for that day fail to update the 'Remaining Time' value.
Adding a new task while existing ones are present in the list correctly updates the 'Remaining Time' field and any alterations to this value are also updated, while attempts to change tasks that were present when the user opened the DayView fail to update.

**Screenshots**
![image](https://user-images.githubusercontent.com/48682900/54535239-05026880-4986-11e9-8f92-471953225394.png)

**Additional context**
N/A

**Comment by DavePCoder** [comment]
Fixed in latest develop for build 103
