### ISSUE TITLE
Programme View: New Tasks can be titled as blank

### ISSUE THREAD

**Issue by MattLCoder** [DavePCoder/CTMS-Issues#50]
Which version of CTMS is the bug found in?
CTMS v5.0 alpha 1 Build 102

**Describe the bug**
As titled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into Programme View.
2. Select a programme and add a new task.
3. On the title field on right panel, clear out field.
4. Deselect the newly created task (select another or click away)

**Expected behaviour**
These blank tasks appear in listing, can be very difficult to select with mouse, but can be selected using cursor keys to move up/down list.

**Additional context**
Recommend if Title field blank, force title value to reset to 'NEW TASK', or prompt user to fill in title.

**Comment by DavePCoder** [comment]
Fixed - when leaving blank as soon as you move off the field it becomes "Unnamed"
